name: Matrix filter release
description: 'Simple application to allow release of mono-repos deployments'
inputs:
  token:
    description: 'Github token'
    required: true
  list:
    description: 'List to filter'
    required: true
  ref:
    description: 'Ref, example master or branch name'
    required: false
  repository:
    description: 'Repository name'
    required: false
outputs:
  filtered:
    description: 'Filtered list'
runs:
  using: 'node20'
  main: 'dist/index.js'
