name: Matrix filter release
description: 'Simple application to allow release of mono-repos deployments'
inputs:
  token:
    description: 'Github token'
    required: true
  list:
    description: 'List to filter'
    required: true
  ref:
    description: 'Ref, example master or branch name'
    required: false
  repository:
    description: 'Repository name'
    required: false
  filter_by:
    description: 'Filter by, to support complex json object paths for example: service.name'
    required: false
    default: 'service'
  is_slice:
    description: 'Is slice, to support slice of the list'
    required: false
    default: 'false'
outputs:
  filtered:
    description: 'Filtered list'
runs:
  using: 'node20'
  main: 'dist/index.js'
